name: CI_CD-Workshop
on:
  push:
    branches:
    - v[0-9]+.[0-9]+

jobs:
  slackNotification:
    name: Slack Notification
    if: (!contains(github.event.head_commit.message, '#NORUN'))
    runs-on: ubuntu-latest
    permissions: {}
    steps:
        - name: Checkout code
          uses: actions/checkout@v3

        - name: Run Trivy vulnerability scanner in fs mode
          uses: aquasecurity/trivy-action@master
          with:
            scan-type: 'fs'
            ignore-unfixed: true
            format: 'table'
            output: 'trivy-results.txt'
            # severity: ${{vars.TRIVY_KEY}}
            severity: CRITICAL
            exit-code: 1

        # Send Slack notification
        - name: Slack Notification
          if: ${{ success() }}
          uses: rtCamp/action-slack-notify@v2
          env:
              SLACK_TITLE: "Image build and signed"
              SLACK_MESSAGE: |
                Name: Ingyin May
                Matriculation: A0290836W
                Email: e1327867@u.nus.edu
                GitHub: https://github.com/riri97-igm/CI_CD-Workshop.git
              SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
              SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        - name: Set up QEMU
          uses: docker/setup-qemu-action@v3

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v3

        - name: Login to Docker Hub
          uses: docker/login-action@v3
          with:
            username: ${{ secrets.DOCKERHUB_USERNAME }}
            password: ${{ secrets.DOCKERHUB_TOKEN }}
        -
          name: Build and push
          uses: docker/build-push-action@v5
          with:
            push: true
            tags: user/app:latest

        # # Send Slack notification
        # - name: Slack Notification
        #   if: ${{ failure() }}
        #   uses: rtCamp/action-slack-notify@v2
        #   env:
        #       SLACK_TITLE: "Image build and signed"
        #       SLACK_MESSAGE: "Fail trivy scan, Check the report for details"
        #       SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK_URL }}
        #       SLACK_WEBHOOK_TYPE: INCOMING_WEBHOOK

        # - name: file upload
        #   if: ${{ failure() }}
        #   uses: MeilCli/slack-upload-file@v4
        #   with:
        #     slack_token: ${{ secrets.SLACK_BOT_TOKEN }}
        #     channel_id: ${{ secrets.SLACK_CHANNEL_ID }}
        #     content: 'file content'
        #     file_path: 'trivy-results.txt'
        #     initial_comment: 'post by slack-upload-file'
