name: Build and Push
on:
  push:
    branches:
    - master

jobs:
  build:
    name: Build
    runs-on: ubuntu-20.04
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Run Trivy vulnerability scanner in fs mode
      uses: aquasecurity/trivy-action@master
      with:
        scan-type: 'fs'
        exit-code: 1
        # severity: ${{vars.TRIVY_KEY}}
        severity: CRITICAL
